apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-reqr
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0024-tenant/tkrw-pr712-0075-0024-app/devfile-sample-reqr@sha256:257a4b508b4f438635be6f61321ee9fea7c94e999e002b31b53fb23ad786bee5
        name: my-nodejs
        resources: {}
status: {}
